name: mergesubjects tests
on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/mergesubjects/**'
      - '!**.md'
  pull_request:
    paths:
      - 'infrastructure/mergesubjects/**'
      - '!**.md'

jobs:
  tests:
    name: Run pytests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/mergesubjects

    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pandas
          
      - name: Run tests
        run: pytest test_mergesubjects_v01.py -v -s
